language: objective-c

script:
  - xctool -project Samples/DynamicServer/DynamicServer.xcodeproj -scheme DynamicServer build
  - xctool -project Samples/iPhoneHTTPServer/iPhoneHTTPServer.xcodeproj -scheme iPhoneHTTPServer -sdk iphonesimulator build
  - xctool -project Samples/PasswdHTTPServer/PasswdHTTPServer.xcodeproj -scheme PasswdHTTPServer build
  - xctool -project Samples/PostHTTPServer/PostHTTPServer.xcodeproj -scheme PostHTTPServer build
  - xctool -project Samples/SecureHTTPServer/SecureHTTPServer.xcodeproj -scheme SecureHTTPServer build
  - xctool -project Samples/SecureWebSocketServer/SecureWebSocketServer.xcodeproj -scheme SecureWebSocketServer build
  - xctool -project Samples/SimpleFileUploadServer/SimpleFileUploadServer.xcodeproj -scheme SimpleFileUploadServer build
  - xctool -project Samples/SimpleHTTPServer/SimpleHTTPServer.xcodeproj -scheme SimpleHTTPServer build
  - xctool -project Samples/SimpleWebSocketServer/SimpleWebSocketServer.xcodeproj -scheme SimpleWebSocketServer build
  - xctool -project Samples/WebDAVServer/WebDAVServer.xcodeproj -scheme WebDAVServer build
